
name: CI

on:
  schedule:
     - cron:  '*/5 * * * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [assigned , unassigned]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Get Value
        env: echo ${{secrets.MYTEXT}}
        run: echo ${{with}}
      - name: Run a one-line script
        run: echo Hello, World
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
