
name: Daily

on:
  schedule:
   - cron: '10 12 * * *'
  workflow_dispatch:
env:
 MAIL_USER_EMAIL: ${{secrets.MAIL_USER_EMAIL}}
 MAIL_USER_PASSWORD: ${{secrets.MAIL_USER_PASSWORD}}
 MAIL_FROM: ${{secrets.MAIL_FROM}}
 MAIL_TO: ${{secrets.MAIL_TO}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
         node-version: '16'
      - run: npm install
      - run: npm run wdio
#       - run: npm run sendreport
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-result-report
          path: reports/report.json
