
name: CI

on:
  schedule:
     - cron:  '* * * * *'
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
         node-version: '16'
      - run: npm install
      - run: npm run wdio
      - uses: dawidd6/action-send-mail@v3
        with:
         server_address: smtp.gmail.com 
         server_port: 465
         subject: Github Actions job result
         to: ayush.hakhu@gmail.com
         from: Ayush Hakhu  
         attachments: ./Results/*.log
         priority: low
